apiVersion: v1
data:
  auth-password: bXktc2VjcmV0LXB3
  root-password: c2VjdXJlLXJvb3QtcHc=
  secret-key: eGNvMHNyMGZoNGU1MngwM2c5bXY=
kind: Secret
metadata:
  creationTimestamp: "2025-03-17T21:28:46Z"
  name: mysql-secret
  namespace: default
  resourceVersion: "1787"
  uid: ea2e7ef0-f8f0-4c32-96cf-ba9e36ccb73e
type: Opaque